services:
  mds-api:
    container_name: mds-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    ports:
      - 9000:9000
    environment:
      - STORE_CORS=${STORE_CORS}
      - ADMIN_CORS=${ADMIN_CORS}
      - AUTH_CORS=${AUTH_CORS}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    depends_on:
      - mds-db

  mds-db:
    image: postgres:16.3-alpine3.20
    container_name: mds-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - mds-db-data:/var/lib/postgresql/data

volumes:
  mds-db-data:
